---
- name: install openvpn on instance
  hosts: vpn-server
  gather_facts: true
  tasks:
    - name: run apt-get update and install python
      raw: "{{ item }}"
      loop:
        - sudo apt-get update
        - sudo apt-get -y install python
      become: true
      ignore_errors: true

- hosts: vpn-server
  become: true
  become_user: root
  become_method: sudo
  roles:
    - openvpn

